lista = list()
l1 = float(input('1º número: '))
lista.append(l1)
l2 = float(input('2º número: '))
lista.append(l2)
l3 = float(input('3º número: '))
lista.append(l3)
print(f'Números inseridos: {lista}')
print(f'O maior entre eles é: {max(lista)}')